(cl:in-package agv_msgs-msg)
(cl:export '(CLASS_ID-VAL
          CLASS_ID
          CLASS_NAME-VAL
          CLASS_NAME
          PROBABILITY-VAL
          PROBABILITY
          TRACK_ID-VAL
          TRACK_ID
          XMIN-VAL
          XMIN
          YMIN-VAL
          YMIN
          XMAX-VAL
          XMAX
          YMAX-VAL
          YMAX
          YAW_HOR-VAL
          YAW_HOR
          YAW_HOR_DEV-VAL
          YAW_HOR_DEV
          YAW_VER-VAL
          YAW_VER
          YAW_VER_DEV-VAL
          YAW_VER_DEV
          DIST-VAL
          DIST
          DIST_DEV-VAL
          DIST_DEV
))