// Generated by gencpp from file agv_msgs/BezierSplinePointWProperties.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_BEZIERSPLINEPOINTWPROPERTIES_H
#define AGV_MSGS_MESSAGE_BEZIERSPLINEPOINTWPROPERTIES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <agv_msgs/SplineDriveParam.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct BezierSplinePointWProperties_
{
  typedef BezierSplinePointWProperties_<ContainerAllocator> Type;

  BezierSplinePointWProperties_()
    : header()
    , coord()
    , cp0()
    , cp1()
    , drive_param()  {
    }
  BezierSplinePointWProperties_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coord(_alloc)
    , cp0(_alloc)
    , cp1(_alloc)
    , drive_param(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _coord_type;
  _coord_type coord;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _cp0_type;
  _cp0_type cp0;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _cp1_type;
  _cp1_type cp1;

   typedef std::vector< ::agv_msgs::SplineDriveParam_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::agv_msgs::SplineDriveParam_<ContainerAllocator> >> _drive_param_type;
  _drive_param_type drive_param;





  typedef boost::shared_ptr< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> const> ConstPtr;

}; // struct BezierSplinePointWProperties_

typedef ::agv_msgs::BezierSplinePointWProperties_<std::allocator<void> > BezierSplinePointWProperties;

typedef boost::shared_ptr< ::agv_msgs::BezierSplinePointWProperties > BezierSplinePointWPropertiesPtr;
typedef boost::shared_ptr< ::agv_msgs::BezierSplinePointWProperties const> BezierSplinePointWPropertiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator1> & lhs, const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.coord == rhs.coord &&
    lhs.cp0 == rhs.cp0 &&
    lhs.cp1 == rhs.cp1 &&
    lhs.drive_param == rhs.drive_param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator1> & lhs, const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cdbfbe79a6088558695ff1f7bb13843";
  }

  static const char* value(const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cdbfbe79a608855ULL;
  static const uint64_t static_value2 = 0x8695ff1f7bb13843ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/BezierSplinePointWProperties";
  }

  static const char* value(const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point coord\n"
"geometry_msgs/Point cp0\n"
"geometry_msgs/Point cp1\n"
"agv_msgs/SplineDriveParam[] drive_param\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/SplineDriveParam\n"
"float64 position_offset\n"
"float64 desired_v\n"
"float64 max_a\n"
"float64 incline_angle\n"
;
  }

  static const char* value(const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coord);
      stream.next(m.cp0);
      stream.next(m.cp1);
      stream.next(m.drive_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BezierSplinePointWProperties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::BezierSplinePointWProperties_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coord: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.coord);
    s << indent << "cp0: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.cp0);
    s << indent << "cp1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.cp1);
    s << indent << "drive_param[]" << std::endl;
    for (size_t i = 0; i < v.drive_param.size(); ++i)
    {
      s << indent << "  drive_param[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::SplineDriveParam_<ContainerAllocator> >::stream(s, indent + "    ", v.drive_param[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_BEZIERSPLINEPOINTWPROPERTIES_H
