// Generated by gencpp from file agv_msgs/EnumStamped.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ENUMSTAMPED_H
#define AGV_MSGS_MESSAGE_ENUMSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct EnumStamped_
{
  typedef EnumStamped_<ContainerAllocator> Type;

  EnumStamped_()
    : header()
    , id(0)
    , name()  {
    }
  EnumStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::agv_msgs::EnumStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::EnumStamped_<ContainerAllocator> const> ConstPtr;

}; // struct EnumStamped_

typedef ::agv_msgs::EnumStamped_<std::allocator<void> > EnumStamped;

typedef boost::shared_ptr< ::agv_msgs::EnumStamped > EnumStampedPtr;
typedef boost::shared_ptr< ::agv_msgs::EnumStamped const> EnumStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::EnumStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::EnumStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::EnumStamped_<ContainerAllocator1> & lhs, const ::agv_msgs::EnumStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::EnumStamped_<ContainerAllocator1> & lhs, const ::agv_msgs::EnumStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::EnumStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::EnumStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::EnumStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::EnumStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::EnumStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::EnumStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::EnumStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12943eb04d4ec5dc013d361ad42949a4";
  }

  static const char* value(const ::agv_msgs::EnumStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12943eb04d4ec5dcULL;
  static const uint64_t static_value2 = 0x013d361ad42949a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::EnumStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/EnumStamped";
  }

  static const char* value(const ::agv_msgs::EnumStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::EnumStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64  id\n"
"string name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::agv_msgs::EnumStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::EnumStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnumStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::EnumStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::EnumStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ENUMSTAMPED_H
