// Generated by gencpp from file agv_msgs/IDs.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_IDS_H
#define AGV_MSGS_MESSAGE_IDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_msgs/ID.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct IDs_
{
  typedef IDs_<ContainerAllocator> Type;

  IDs_()
    : ids()  {
    }
  IDs_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::agv_msgs::ID_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::agv_msgs::ID_<ContainerAllocator> >> _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::agv_msgs::IDs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::IDs_<ContainerAllocator> const> ConstPtr;

}; // struct IDs_

typedef ::agv_msgs::IDs_<std::allocator<void> > IDs;

typedef boost::shared_ptr< ::agv_msgs::IDs > IDsPtr;
typedef boost::shared_ptr< ::agv_msgs::IDs const> IDsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::IDs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::IDs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::IDs_<ContainerAllocator1> & lhs, const ::agv_msgs::IDs_<ContainerAllocator2> & rhs)
{
  return lhs.ids == rhs.ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::IDs_<ContainerAllocator1> & lhs, const ::agv_msgs::IDs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::IDs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::IDs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::IDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::IDs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::IDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::IDs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d86b5640038c0900844695683d4a6029";
  }

  static const char* value(const ::agv_msgs::IDs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd86b5640038c0900ULL;
  static const uint64_t static_value2 = 0x844695683d4a6029ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/IDs";
  }

  static const char* value(const ::agv_msgs::IDs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::IDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ID[] ids\n"
"================================================================================\n"
"MSG: agv_msgs/ID\n"
" uint32 data\n"
"\n"
" uint32 INVALID_ID=0\n"
;
  }

  static const char* value(const ::agv_msgs::IDs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::IDs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IDs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::IDs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::IDs_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::ID_<ContainerAllocator> >::stream(s, indent + "    ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_IDS_H
