// Generated by gencpp from file agv_msgs/LidarTrackingArray.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_LIDARTRACKINGARRAY_H
#define AGV_MSGS_MESSAGE_LIDARTRACKINGARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int64MultiArray.h>
#include <jsk_recognition_msgs/BoundingBoxArray.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct LidarTrackingArray_
{
  typedef LidarTrackingArray_<ContainerAllocator> Type;

  LidarTrackingArray_()
    : ids()
    , bboxes()  {
    }
  LidarTrackingArray_(const ContainerAllocator& _alloc)
    : ids(_alloc)
    , bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int64MultiArray_<ContainerAllocator>  _ids_type;
  _ids_type ids;

   typedef  ::jsk_recognition_msgs::BoundingBoxArray_<ContainerAllocator>  _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> const> ConstPtr;

}; // struct LidarTrackingArray_

typedef ::agv_msgs::LidarTrackingArray_<std::allocator<void> > LidarTrackingArray;

typedef boost::shared_ptr< ::agv_msgs::LidarTrackingArray > LidarTrackingArrayPtr;
typedef boost::shared_ptr< ::agv_msgs::LidarTrackingArray const> LidarTrackingArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::LidarTrackingArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::LidarTrackingArray_<ContainerAllocator1> & lhs, const ::agv_msgs::LidarTrackingArray_<ContainerAllocator2> & rhs)
{
  return lhs.ids == rhs.ids &&
    lhs.bboxes == rhs.bboxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::LidarTrackingArray_<ContainerAllocator1> & lhs, const ::agv_msgs::LidarTrackingArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "941673c615d47028c6cf33c8aedc0d50";
  }

  static const char* value(const ::agv_msgs::LidarTrackingArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x941673c615d47028ULL;
  static const uint64_t static_value2 = 0xc6cf33c8aedc0d50ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/LidarTrackingArray";
  }

  static const char* value(const ::agv_msgs::LidarTrackingArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int64MultiArray ids\n"
"jsk_recognition_msgs/BoundingBoxArray bboxes\n"
"================================================================================\n"
"MSG: std_msgs/Int64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int64[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBoxArray\n"
"# BoundingBoxArray is a list of BoundingBox.\n"
"# You can use jsk_rviz_plugins to visualize BoungingBoxArray on rviz.\n"
"Header header\n"
"BoundingBox[] boxes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::agv_msgs::LidarTrackingArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarTrackingArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::LidarTrackingArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::LidarTrackingArray_<ContainerAllocator>& v)
  {
    s << indent << "ids: ";
    s << std::endl;
    Printer< ::std_msgs::Int64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.ids);
    s << indent << "bboxes: ";
    s << std::endl;
    Printer< ::jsk_recognition_msgs::BoundingBoxArray_<ContainerAllocator> >::stream(s, indent + "  ", v.bboxes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_LIDARTRACKINGARRAY_H
