// Generated by gencpp from file agv_msgs/MissionInstrumentation.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_MISSIONINSTRUMENTATION_H
#define AGV_MSGS_MESSAGE_MISSIONINSTRUMENTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct MissionInstrumentation_
{
  typedef MissionInstrumentation_<ContainerAllocator> Type;

  MissionInstrumentation_()
    : elapsed_time()
    , traversed_distance(0.0)  {
    }
  MissionInstrumentation_(const ContainerAllocator& _alloc)
    : elapsed_time()
    , traversed_distance(0.0)  {
  (void)_alloc;
    }



   typedef ros::Duration _elapsed_time_type;
  _elapsed_time_type elapsed_time;

   typedef double _traversed_distance_type;
  _traversed_distance_type traversed_distance;





  typedef boost::shared_ptr< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> const> ConstPtr;

}; // struct MissionInstrumentation_

typedef ::agv_msgs::MissionInstrumentation_<std::allocator<void> > MissionInstrumentation;

typedef boost::shared_ptr< ::agv_msgs::MissionInstrumentation > MissionInstrumentationPtr;
typedef boost::shared_ptr< ::agv_msgs::MissionInstrumentation const> MissionInstrumentationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::MissionInstrumentation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::MissionInstrumentation_<ContainerAllocator1> & lhs, const ::agv_msgs::MissionInstrumentation_<ContainerAllocator2> & rhs)
{
  return lhs.elapsed_time == rhs.elapsed_time &&
    lhs.traversed_distance == rhs.traversed_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::MissionInstrumentation_<ContainerAllocator1> & lhs, const ::agv_msgs::MissionInstrumentation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0f51d602a0058a2f553df8c1db261b2";
  }

  static const char* value(const ::agv_msgs::MissionInstrumentation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0f51d602a0058a2ULL;
  static const uint64_t static_value2 = 0xf553df8c1db261b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/MissionInstrumentation";
  }

  static const char* value(const ::agv_msgs::MissionInstrumentation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duration elapsed_time\n"
"float64 traversed_distance\n"
;
  }

  static const char* value(const ::agv_msgs::MissionInstrumentation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elapsed_time);
      stream.next(m.traversed_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionInstrumentation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::MissionInstrumentation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::MissionInstrumentation_<ContainerAllocator>& v)
  {
    s << indent << "elapsed_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.elapsed_time);
    s << indent << "traversed_distance: ";
    Printer<double>::stream(s, indent + "  ", v.traversed_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_MISSIONINSTRUMENTATION_H
