// Generated by gencpp from file agv_msgs/Obstacle.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_OBSTACLE_H
#define AGV_MSGS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <agv_msgs/ObstacleInfo.h>
#include <agv_msgs/ObstacleShape.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : header()
    , info()
    , shape()  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)
    , shape(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::agv_msgs::ObstacleInfo_<ContainerAllocator>  _info_type;
  _info_type info;

   typedef  ::agv_msgs::ObstacleShape_<ContainerAllocator>  _shape_type;
  _shape_type shape;





  typedef boost::shared_ptr< ::agv_msgs::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::agv_msgs::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::agv_msgs::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::agv_msgs::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::agv_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.info == rhs.info &&
    lhs.shape == rhs.shape;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::agv_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9a9ae43bd863b8343b3c3c58447e9df";
  }

  static const char* value(const ::agv_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9a9ae43bd863b83ULL;
  static const uint64_t static_value2 = 0x43b3c3c58447e9dfULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/Obstacle";
  }

  static const char* value(const ::agv_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"agv_msgs/ObstacleInfo info\n"
"agv_msgs/ObstacleShape shape \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/ObstacleInfo\n"
"string description\n"
"uint16 symbol\n"
"agv_msgs/ID layer_id\n"
"bool enabled\n"
"uint16 priority\n"
"\n"
"uint8 operation\n"
"uint8 REPLACE = 0\n"
"uint8 ADD = 1\n"
"uint8 SUBTRACT = 2\n"
"================================================================================\n"
"MSG: agv_msgs/ID\n"
" uint32 data\n"
"\n"
" uint32 INVALID_ID=0\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/ObstacleShape\n"
"agv_msgs/ID id\n"
"geometry_msgs/Point32[] points \n"
"float32 cost\n"
"float32 radius\n"
"string frame_id\n"
"\n"
"uint8 type\n"
"uint8 INVALID = 0\n"
"uint8 POLYGON = 1\n"
"uint8 RADIUS = 2 \n"
"uint8 BARRIER = 3  \n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::agv_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
      stream.next(m.shape);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info: ";
    s << std::endl;
    Printer< ::agv_msgs::ObstacleInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
    s << indent << "shape: ";
    s << std::endl;
    Printer< ::agv_msgs::ObstacleShape_<ContainerAllocator> >::stream(s, indent + "  ", v.shape);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_OBSTACLE_H
