// Generated by gencpp from file agv_msgs/ObstacleLayer.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_OBSTACLELAYER_H
#define AGV_MSGS_MESSAGE_OBSTACLELAYER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_msgs/ID.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct ObstacleLayer_
{
  typedef ObstacleLayer_<ContainerAllocator> Type;

  ObstacleLayer_()
    : name()
    , id()
    , color()
    , order(0)  {
      color.assign(0);
  }
  ObstacleLayer_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , id(_alloc)
    , color()
    , order(0)  {
  (void)_alloc;
      color.assign(0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::agv_msgs::ID_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef boost::array<uint8_t, 4>  _color_type;
  _color_type color;

   typedef uint8_t _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::agv_msgs::ObstacleLayer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ObstacleLayer_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleLayer_

typedef ::agv_msgs::ObstacleLayer_<std::allocator<void> > ObstacleLayer;

typedef boost::shared_ptr< ::agv_msgs::ObstacleLayer > ObstacleLayerPtr;
typedef boost::shared_ptr< ::agv_msgs::ObstacleLayer const> ObstacleLayerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ObstacleLayer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ObstacleLayer_<ContainerAllocator1> & lhs, const ::agv_msgs::ObstacleLayer_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.id == rhs.id &&
    lhs.color == rhs.color &&
    lhs.order == rhs.order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ObstacleLayer_<ContainerAllocator1> & lhs, const ::agv_msgs::ObstacleLayer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ObstacleLayer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ObstacleLayer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ObstacleLayer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bd0537b4fe7e49768bd2ae71fd5bb22";
  }

  static const char* value(const ::agv_msgs::ObstacleLayer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bd0537b4fe7e497ULL;
  static const uint64_t static_value2 = 0x68bd2ae71fd5bb22ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ObstacleLayer";
  }

  static const char* value(const ::agv_msgs::ObstacleLayer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"agv_msgs/ID id\n"
"uint8[4] color\n"
"uint8 order\n"
"================================================================================\n"
"MSG: agv_msgs/ID\n"
" uint32 data\n"
"\n"
" uint32 INVALID_ID=0\n"
;
  }

  static const char* value(const ::agv_msgs::ObstacleLayer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.id);
      stream.next(m.color);
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleLayer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ObstacleLayer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ObstacleLayer_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    s << std::endl;
    Printer< ::agv_msgs::ID_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.color[i]);
    }
    s << indent << "order: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_OBSTACLELAYER_H
