// Generated by gencpp from file agv_msgs/PlaneCoefs.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_PLANECOEFS_H
#define AGV_MSGS_MESSAGE_PLANECOEFS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <shape_msgs/Plane.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct PlaneCoefs_
{
  typedef PlaneCoefs_<ContainerAllocator> Type;

  PlaneCoefs_()
    : header()
    , plane()  {
    }
  PlaneCoefs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , plane(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::shape_msgs::Plane_<ContainerAllocator>  _plane_type;
  _plane_type plane;





  typedef boost::shared_ptr< ::agv_msgs::PlaneCoefs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::PlaneCoefs_<ContainerAllocator> const> ConstPtr;

}; // struct PlaneCoefs_

typedef ::agv_msgs::PlaneCoefs_<std::allocator<void> > PlaneCoefs;

typedef boost::shared_ptr< ::agv_msgs::PlaneCoefs > PlaneCoefsPtr;
typedef boost::shared_ptr< ::agv_msgs::PlaneCoefs const> PlaneCoefsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::PlaneCoefs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::PlaneCoefs_<ContainerAllocator1> & lhs, const ::agv_msgs::PlaneCoefs_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.plane == rhs.plane;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::PlaneCoefs_<ContainerAllocator1> & lhs, const ::agv_msgs::PlaneCoefs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::PlaneCoefs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::PlaneCoefs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::PlaneCoefs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c3e20d1e0ce2c692b0df82d8f7c0a1e";
  }

  static const char* value(const ::agv_msgs::PlaneCoefs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c3e20d1e0ce2c69ULL;
  static const uint64_t static_value2 = 0x2b0df82d8f7c0a1eULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/PlaneCoefs";
  }

  static const char* value(const ::agv_msgs::PlaneCoefs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"shape_msgs/Plane plane\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: shape_msgs/Plane\n"
"# Representation of a plane, using the plane equation ax + by + cz + d = 0\n"
"\n"
"# a := coef[0]\n"
"# b := coef[1]\n"
"# c := coef[2]\n"
"# d := coef[3]\n"
"\n"
"float64[4] coef\n"
;
  }

  static const char* value(const ::agv_msgs::PlaneCoefs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.plane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaneCoefs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::PlaneCoefs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::PlaneCoefs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "plane: ";
    s << std::endl;
    Printer< ::shape_msgs::Plane_<ContainerAllocator> >::stream(s, indent + "  ", v.plane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_PLANECOEFS_H
