// Generated by gencpp from file agv_msgs/RfTagInfo.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_RFTAGINFO_H
#define AGV_MSGS_MESSAGE_RFTAGINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct RfTagInfo_
{
  typedef RfTagInfo_<ContainerAllocator> Type;

  RfTagInfo_()
    : header()
    , tag_addr()
    , anchor_addr()
    , dist_to_anchor(0.0)
    , tag_frame(0)
    , btn0_state(false)
    , btn1_state(false)
    , btn2_state(false)
    , battery_lvl(0)
    , first_path_power(0.0)
    , received_signal_strength(0.0)
    , covariance(0.0)  {
    }
  RfTagInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag_addr(_alloc)
    , anchor_addr(_alloc)
    , dist_to_anchor(0.0)
    , tag_frame(0)
    , btn0_state(false)
    , btn1_state(false)
    , btn2_state(false)
    , battery_lvl(0)
    , first_path_power(0.0)
    , received_signal_strength(0.0)
    , covariance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_addr_type;
  _tag_addr_type tag_addr;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _anchor_addr_type;
  _anchor_addr_type anchor_addr;

   typedef float _dist_to_anchor_type;
  _dist_to_anchor_type dist_to_anchor;

   typedef uint8_t _tag_frame_type;
  _tag_frame_type tag_frame;

   typedef uint8_t _btn0_state_type;
  _btn0_state_type btn0_state;

   typedef uint8_t _btn1_state_type;
  _btn1_state_type btn1_state;

   typedef uint8_t _btn2_state_type;
  _btn2_state_type btn2_state;

   typedef uint8_t _battery_lvl_type;
  _battery_lvl_type battery_lvl;

   typedef float _first_path_power_type;
  _first_path_power_type first_path_power;

   typedef float _received_signal_strength_type;
  _received_signal_strength_type received_signal_strength;

   typedef float _covariance_type;
  _covariance_type covariance;





  typedef boost::shared_ptr< ::agv_msgs::RfTagInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::RfTagInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RfTagInfo_

typedef ::agv_msgs::RfTagInfo_<std::allocator<void> > RfTagInfo;

typedef boost::shared_ptr< ::agv_msgs::RfTagInfo > RfTagInfoPtr;
typedef boost::shared_ptr< ::agv_msgs::RfTagInfo const> RfTagInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::RfTagInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::RfTagInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::RfTagInfo_<ContainerAllocator1> & lhs, const ::agv_msgs::RfTagInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag_addr == rhs.tag_addr &&
    lhs.anchor_addr == rhs.anchor_addr &&
    lhs.dist_to_anchor == rhs.dist_to_anchor &&
    lhs.tag_frame == rhs.tag_frame &&
    lhs.btn0_state == rhs.btn0_state &&
    lhs.btn1_state == rhs.btn1_state &&
    lhs.btn2_state == rhs.btn2_state &&
    lhs.battery_lvl == rhs.battery_lvl &&
    lhs.first_path_power == rhs.first_path_power &&
    lhs.received_signal_strength == rhs.received_signal_strength &&
    lhs.covariance == rhs.covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::RfTagInfo_<ContainerAllocator1> & lhs, const ::agv_msgs::RfTagInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::RfTagInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::RfTagInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::RfTagInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b788a49c92ea14828852cd337a50704a";
  }

  static const char* value(const ::agv_msgs::RfTagInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb788a49c92ea1482ULL;
  static const uint64_t static_value2 = 0x8852cd337a50704aULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/RfTagInfo";
  }

  static const char* value(const ::agv_msgs::RfTagInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string tag_addr\n"
"string anchor_addr\n"
"float32 dist_to_anchor\n"
"uint8 tag_frame\n"
"bool btn0_state\n"
"bool btn1_state\n"
"bool btn2_state\n"
"uint8 battery_lvl\n"
"float32 first_path_power\n"
"float32 received_signal_strength\n"
"float32 covariance\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::agv_msgs::RfTagInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag_addr);
      stream.next(m.anchor_addr);
      stream.next(m.dist_to_anchor);
      stream.next(m.tag_frame);
      stream.next(m.btn0_state);
      stream.next(m.btn1_state);
      stream.next(m.btn2_state);
      stream.next(m.battery_lvl);
      stream.next(m.first_path_power);
      stream.next(m.received_signal_strength);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RfTagInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::RfTagInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::RfTagInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tag_addr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag_addr);
    s << indent << "anchor_addr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.anchor_addr);
    s << indent << "dist_to_anchor: ";
    Printer<float>::stream(s, indent + "  ", v.dist_to_anchor);
    s << indent << "tag_frame: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag_frame);
    s << indent << "btn0_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.btn0_state);
    s << indent << "btn1_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.btn1_state);
    s << indent << "btn2_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.btn2_state);
    s << indent << "battery_lvl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery_lvl);
    s << indent << "first_path_power: ";
    Printer<float>::stream(s, indent + "  ", v.first_path_power);
    s << indent << "received_signal_strength: ";
    Printer<float>::stream(s, indent + "  ", v.received_signal_strength);
    s << indent << "covariance: ";
    Printer<float>::stream(s, indent + "  ", v.covariance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_RFTAGINFO_H
