// Generated by gencpp from file agv_msgs/SetLightState.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_SETLIGHTSTATE_H
#define AGV_MSGS_MESSAGE_SETLIGHTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct SetLightState_
{
  typedef SetLightState_<ContainerAllocator> Type;

  SetLightState_()
    : name()
    , frequency(0.0)
    , duty(0.0)
    , num_periods(0)  {
    }
  SetLightState_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , frequency(0.0)
    , duty(0.0)
    , num_periods(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _frequency_type;
  _frequency_type frequency;

   typedef float _duty_type;
  _duty_type duty;

   typedef uint32_t _num_periods_type;
  _num_periods_type num_periods;





  typedef boost::shared_ptr< ::agv_msgs::SetLightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::SetLightState_<ContainerAllocator> const> ConstPtr;

}; // struct SetLightState_

typedef ::agv_msgs::SetLightState_<std::allocator<void> > SetLightState;

typedef boost::shared_ptr< ::agv_msgs::SetLightState > SetLightStatePtr;
typedef boost::shared_ptr< ::agv_msgs::SetLightState const> SetLightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::SetLightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::SetLightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::SetLightState_<ContainerAllocator1> & lhs, const ::agv_msgs::SetLightState_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.frequency == rhs.frequency &&
    lhs.duty == rhs.duty &&
    lhs.num_periods == rhs.num_periods;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::SetLightState_<ContainerAllocator1> & lhs, const ::agv_msgs::SetLightState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SetLightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SetLightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SetLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SetLightState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SetLightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SetLightState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::SetLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "194cab8d6bb9205433dc15755489711e";
  }

  static const char* value(const ::agv_msgs::SetLightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x194cab8d6bb92054ULL;
  static const uint64_t static_value2 = 0x33dc15755489711eULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::SetLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/SetLightState";
  }

  static const char* value(const ::agv_msgs::SetLightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::SetLightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32 frequency\n"
"float32 duty\n"
"uint32 num_periods\n"
;
  }

  static const char* value(const ::agv_msgs::SetLightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::SetLightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.frequency);
      stream.next(m.duty);
      stream.next(m.num_periods);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::SetLightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::SetLightState_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "frequency: ";
    Printer<float>::stream(s, indent + "  ", v.frequency);
    s << indent << "duty: ";
    Printer<float>::stream(s, indent + "  ", v.duty);
    s << indent << "num_periods: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_periods);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_SETLIGHTSTATE_H
