// Generated by gencpp from file agv_msgs/SplinePathArray.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_SPLINEPATHARRAY_H
#define AGV_MSGS_MESSAGE_SPLINEPATHARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_msgs/SplinePath.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct SplinePathArray_
{
  typedef SplinePathArray_<ContainerAllocator> Type;

  SplinePathArray_()
    : smooth_paths()  {
    }
  SplinePathArray_(const ContainerAllocator& _alloc)
    : smooth_paths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::agv_msgs::SplinePath_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::agv_msgs::SplinePath_<ContainerAllocator> >> _smooth_paths_type;
  _smooth_paths_type smooth_paths;





  typedef boost::shared_ptr< ::agv_msgs::SplinePathArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::SplinePathArray_<ContainerAllocator> const> ConstPtr;

}; // struct SplinePathArray_

typedef ::agv_msgs::SplinePathArray_<std::allocator<void> > SplinePathArray;

typedef boost::shared_ptr< ::agv_msgs::SplinePathArray > SplinePathArrayPtr;
typedef boost::shared_ptr< ::agv_msgs::SplinePathArray const> SplinePathArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::SplinePathArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::SplinePathArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::SplinePathArray_<ContainerAllocator1> & lhs, const ::agv_msgs::SplinePathArray_<ContainerAllocator2> & rhs)
{
  return lhs.smooth_paths == rhs.smooth_paths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::SplinePathArray_<ContainerAllocator1> & lhs, const ::agv_msgs::SplinePathArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SplinePathArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SplinePathArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SplinePathArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05cf4559b25a14e1afdea5a89a416603";
  }

  static const char* value(const ::agv_msgs::SplinePathArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05cf4559b25a14e1ULL;
  static const uint64_t static_value2 = 0xafdea5a89a416603ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/SplinePathArray";
  }

  static const char* value(const ::agv_msgs::SplinePathArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/SplinePath[] smooth_paths\n"
"================================================================================\n"
"MSG: agv_msgs/SplinePath\n"
"Header header\n"
"agv_msgs/BezierSplinePointWProperties[] path\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/BezierSplinePointWProperties\n"
"Header header\n"
"geometry_msgs/Point coord\n"
"geometry_msgs/Point cp0\n"
"geometry_msgs/Point cp1\n"
"agv_msgs/SplineDriveParam[] drive_param\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/SplineDriveParam\n"
"float64 position_offset\n"
"float64 desired_v\n"
"float64 max_a\n"
"float64 incline_angle\n"
;
  }

  static const char* value(const ::agv_msgs::SplinePathArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.smooth_paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SplinePathArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::SplinePathArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::SplinePathArray_<ContainerAllocator>& v)
  {
    s << indent << "smooth_paths[]" << std::endl;
    for (size_t i = 0; i < v.smooth_paths.size(); ++i)
    {
      s << indent << "  smooth_paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::SplinePath_<ContainerAllocator> >::stream(s, indent + "    ", v.smooth_paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_SPLINEPATHARRAY_H
