// Generated by gencpp from file agv_msgs/StringWithIDStamped.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_STRINGWITHIDSTAMPED_H
#define AGV_MSGS_MESSAGE_STRINGWITHIDSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct StringWithIDStamped_
{
  typedef StringWithIDStamped_<ContainerAllocator> Type;

  StringWithIDStamped_()
    : id(0)
    , data()
    , creation_time()  {
    }
  StringWithIDStamped_(const ContainerAllocator& _alloc)
    : id(0)
    , data(_alloc)
    , creation_time()  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef ros::Time _creation_time_type;
  _creation_time_type creation_time;





  typedef boost::shared_ptr< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> const> ConstPtr;

}; // struct StringWithIDStamped_

typedef ::agv_msgs::StringWithIDStamped_<std::allocator<void> > StringWithIDStamped;

typedef boost::shared_ptr< ::agv_msgs::StringWithIDStamped > StringWithIDStampedPtr;
typedef boost::shared_ptr< ::agv_msgs::StringWithIDStamped const> StringWithIDStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::StringWithIDStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::StringWithIDStamped_<ContainerAllocator1> & lhs, const ::agv_msgs::StringWithIDStamped_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.data == rhs.data &&
    lhs.creation_time == rhs.creation_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::StringWithIDStamped_<ContainerAllocator1> & lhs, const ::agv_msgs::StringWithIDStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16d2a98e7f794a9581e118f4dada7d23";
  }

  static const char* value(const ::agv_msgs::StringWithIDStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16d2a98e7f794a95ULL;
  static const uint64_t static_value2 = 0x81e118f4dada7d23ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/StringWithIDStamped";
  }

  static const char* value(const ::agv_msgs::StringWithIDStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"string data\n"
"time creation_time\n"
;
  }

  static const char* value(const ::agv_msgs::StringWithIDStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
      stream.next(m.creation_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringWithIDStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::StringWithIDStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::StringWithIDStamped_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "creation_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.creation_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_STRINGWITHIDSTAMPED_H
