// Generated by gencpp from file agv_msgs/TractionData.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_TRACTIONDATA_H
#define AGV_MSGS_MESSAGE_TRACTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <agv_msgs/MotorData.h>
#include <agv_msgs/MotorData.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct TractionData_
{
  typedef TractionData_<ContainerAllocator> Type;

  TractionData_()
    : header()
    , left()
    , right()  {
    }
  TractionData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::agv_msgs::MotorData_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::agv_msgs::MotorData_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::agv_msgs::TractionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::TractionData_<ContainerAllocator> const> ConstPtr;

}; // struct TractionData_

typedef ::agv_msgs::TractionData_<std::allocator<void> > TractionData;

typedef boost::shared_ptr< ::agv_msgs::TractionData > TractionDataPtr;
typedef boost::shared_ptr< ::agv_msgs::TractionData const> TractionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::TractionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::TractionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::TractionData_<ContainerAllocator1> & lhs, const ::agv_msgs::TractionData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::TractionData_<ContainerAllocator1> & lhs, const ::agv_msgs::TractionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::TractionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::TractionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::TractionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::TractionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::TractionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::TractionData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::TractionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b382b54a342799235e892a0035f8c7b";
  }

  static const char* value(const ::agv_msgs::TractionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b382b54a3427992ULL;
  static const uint64_t static_value2 = 0x35e892a0035f8c7bULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::TractionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/TractionData";
  }

  static const char* value(const ::agv_msgs::TractionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::TractionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"MotorData left\n"
"MotorData right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/MotorData\n"
"EncoderData enc\n"
"float32 torque            # Nm\n"
"float32 current           # A\n"
"float32 voltage           # V\n"
"float32 temperature       # C\n"
"\n"
"# Some useful formulas for reference (use Si units)\n"
"# Mechanical power = torque * angular_velocity\n"
"# Electrical power = current * voltage\n"
"# Efficiency = mech. power / elec. power\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/EncoderData\n"
"float32 velocity\n"
"float32 distance\n"
"\n"
"uint8 units\n"
"uint8 RPM=0     # velocity in rpm,      distance in rotations\n"
"uint8 RAD_S=1   # velocity in rad/s,    distance in radians\n"
"uint8 M_S=2     # velocity in m/s,      distance in metres\n"
"uint8 TICKS=3   # velocity in ticks/s,  distance in ticks\n"
;
  }

  static const char* value(const ::agv_msgs::TractionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::TractionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TractionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::TractionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::TractionData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::agv_msgs::MotorData_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::agv_msgs::MotorData_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_TRACTIONDATA_H
