// Generated by gencpp from file agv_msgs/WaypointArray.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_WAYPOINTARRAY_H
#define AGV_MSGS_MESSAGE_WAYPOINTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_msgs/Waypoint.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct WaypointArray_
{
  typedef WaypointArray_<ContainerAllocator> Type;

  WaypointArray_()
    : points()  {
    }
  WaypointArray_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::agv_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::agv_msgs::Waypoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::agv_msgs::WaypointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::WaypointArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointArray_

typedef ::agv_msgs::WaypointArray_<std::allocator<void> > WaypointArray;

typedef boost::shared_ptr< ::agv_msgs::WaypointArray > WaypointArrayPtr;
typedef boost::shared_ptr< ::agv_msgs::WaypointArray const> WaypointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::WaypointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::WaypointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::agv_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::agv_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b892504f792016845606f79a85c2f15a";
  }

  static const char* value(const ::agv_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb892504f79201684ULL;
  static const uint64_t static_value2 = 0x5606f79a85c2f15aULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/WaypointArray";
  }

  static const char* value(const ::agv_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/Waypoint[] points\n"
"================================================================================\n"
"MSG: agv_msgs/Waypoint\n"
"Header header\n"
"agv_msgs/NavPose pose\n"
"agv_msgs/WaypointStatus status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/NavPose\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 theta\n"
"\n"
"uint8 type\n"
"uint8 UNKNOWN=0\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/WaypointStatus\n"
"agv_msgs/ID goal_id\n"
"uint8 state # contins actionlib::SimpleClientGoalState state\n"
"float32 radius\n"
"bool road\n"
"bool intersection\n"
"================================================================================\n"
"MSG: agv_msgs/ID\n"
" uint32 data\n"
"\n"
" uint32 INVALID_ID=0\n"
;
  }

  static const char* value(const ::agv_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::WaypointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::WaypointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::WaypointArray_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agv_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_WAYPOINTARRAY_H
