// Generated by gencpp from file agv_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_WAYPOINT_H
#define AGV_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <agv_msgs/NavPose.h>
#include <agv_msgs/WaypointStatus.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : header()
    , pose()
    , status()  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::agv_msgs::NavPose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::agv_msgs::WaypointStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::agv_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::agv_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::agv_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::agv_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::agv_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::agv_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e11fc09e9fd5b5c4d82756a0e92bc03b";
  }

  static const char* value(const ::agv_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe11fc09e9fd5b5c4ULL;
  static const uint64_t static_value2 = 0xd82756a0e92bc03bULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/Waypoint";
  }

  static const char* value(const ::agv_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"agv_msgs/NavPose pose\n"
"agv_msgs/WaypointStatus status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/NavPose\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 theta\n"
"\n"
"uint8 type\n"
"uint8 UNKNOWN=0\n"
"\n"
"================================================================================\n"
"MSG: agv_msgs/WaypointStatus\n"
"agv_msgs/ID goal_id\n"
"uint8 state # contins actionlib::SimpleClientGoalState state\n"
"float32 radius\n"
"bool road\n"
"bool intersection\n"
"================================================================================\n"
"MSG: agv_msgs/ID\n"
" uint32 data\n"
"\n"
" uint32 INVALID_ID=0\n"
;
  }

  static const char* value(const ::agv_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::agv_msgs::NavPose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::agv_msgs::WaypointStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_WAYPOINT_H
