// Generated by gencpp from file agv_msgs/ZoneShape.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ZONESHAPE_H
#define AGV_MSGS_MESSAGE_ZONESHAPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct ZoneShape_
{
  typedef ZoneShape_<ContainerAllocator> Type;

  ZoneShape_()
    : frame_id()
    , points()
    , radius(0.0)
    , type(0)  {
    }
  ZoneShape_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , points(_alloc)
    , radius(0.0)
    , type(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef float _radius_type;
  _radius_type radius;

   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INVALID)
  #undef INVALID
#endif
#if defined(_WIN32) && defined(POLYGON)
  #undef POLYGON
#endif
#if defined(_WIN32) && defined(RADIUS)
  #undef RADIUS
#endif
#if defined(_WIN32) && defined(BARRIER)
  #undef BARRIER
#endif

  enum {
    INVALID = 0u,
    POLYGON = 1u,
    RADIUS = 2u,
    BARRIER = 3u,
  };


  typedef boost::shared_ptr< ::agv_msgs::ZoneShape_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ZoneShape_<ContainerAllocator> const> ConstPtr;

}; // struct ZoneShape_

typedef ::agv_msgs::ZoneShape_<std::allocator<void> > ZoneShape;

typedef boost::shared_ptr< ::agv_msgs::ZoneShape > ZoneShapePtr;
typedef boost::shared_ptr< ::agv_msgs::ZoneShape const> ZoneShapeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ZoneShape_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ZoneShape_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ZoneShape_<ContainerAllocator1> & lhs, const ::agv_msgs::ZoneShape_<ContainerAllocator2> & rhs)
{
  return lhs.frame_id == rhs.frame_id &&
    lhs.points == rhs.points &&
    lhs.radius == rhs.radius &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ZoneShape_<ContainerAllocator1> & lhs, const ::agv_msgs::ZoneShape_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ZoneShape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ZoneShape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ZoneShape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ZoneShape_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ZoneShape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ZoneShape_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ZoneShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a50b2727b92148a1d88f37b509d9c8f1";
  }

  static const char* value(const ::agv_msgs::ZoneShape_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa50b2727b92148a1ULL;
  static const uint64_t static_value2 = 0xd88f37b509d9c8f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ZoneShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ZoneShape";
  }

  static const char* value(const ::agv_msgs::ZoneShape_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ZoneShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame_id\n"
"geometry_msgs/Point32[] points\n"
"float32 radius\n"
"\n"
"uint8 type\n"
"uint8 INVALID = 0\n"
"uint8 POLYGON = 1\n"
"uint8 RADIUS = 2 \n"
"uint8 BARRIER = 3  \n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::agv_msgs::ZoneShape_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ZoneShape_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.points);
      stream.next(m.radius);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZoneShape_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ZoneShape_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ZoneShape_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ZONESHAPE_H
