# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_msgs/MissionInstrumentation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class MissionInstrumentation(genpy.Message):
  _md5sum = "a0f51d602a0058a2f553df8c1db261b2"
  _type = "agv_msgs/MissionInstrumentation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """duration elapsed_time
float64 traversed_distance
"""
  __slots__ = ['elapsed_time','traversed_distance']
  _slot_types = ['duration','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       elapsed_time,traversed_distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionInstrumentation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.elapsed_time is None:
        self.elapsed_time = genpy.Duration()
      if self.traversed_distance is None:
        self.traversed_distance = 0.
    else:
      self.elapsed_time = genpy.Duration()
      self.traversed_distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2id().pack(_x.elapsed_time.secs, _x.elapsed_time.nsecs, _x.traversed_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.elapsed_time is None:
        self.elapsed_time = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.elapsed_time.secs, _x.elapsed_time.nsecs, _x.traversed_distance,) = _get_struct_2id().unpack(str[start:end])
      self.elapsed_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2id().pack(_x.elapsed_time.secs, _x.elapsed_time.nsecs, _x.traversed_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.elapsed_time is None:
        self.elapsed_time = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.elapsed_time.secs, _x.elapsed_time.nsecs, _x.traversed_distance,) = _get_struct_2id().unpack(str[start:end])
      self.elapsed_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2id = None
def _get_struct_2id():
    global _struct_2id
    if _struct_2id is None:
        _struct_2id = struct.Struct("<2id")
    return _struct_2id
