# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_msgs/ObstacleInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import agv_msgs.msg

class ObstacleInfo(genpy.Message):
  _md5sum = "77a1e000112bcc70c977607dda6c239e"
  _type = "agv_msgs/ObstacleInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string description
uint16 symbol
agv_msgs/ID layer_id
bool enabled
uint16 priority

uint8 operation
uint8 REPLACE = 0
uint8 ADD = 1
uint8 SUBTRACT = 2
================================================================================
MSG: agv_msgs/ID
 uint32 data

 uint32 INVALID_ID=0
"""
  # Pseudo-constants
  REPLACE = 0
  ADD = 1
  SUBTRACT = 2

  __slots__ = ['description','symbol','layer_id','enabled','priority','operation']
  _slot_types = ['string','uint16','agv_msgs/ID','bool','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       description,symbol,layer_id,enabled,priority,operation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.description is None:
        self.description = ''
      if self.symbol is None:
        self.symbol = 0
      if self.layer_id is None:
        self.layer_id = agv_msgs.msg.ID()
      if self.enabled is None:
        self.enabled = False
      if self.priority is None:
        self.priority = 0
      if self.operation is None:
        self.operation = 0
    else:
      self.description = ''
      self.symbol = 0
      self.layer_id = agv_msgs.msg.ID()
      self.enabled = False
      self.priority = 0
      self.operation = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HIBHB().pack(_x.symbol, _x.layer_id.data, _x.enabled, _x.priority, _x.operation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.layer_id is None:
        self.layer_id = agv_msgs.msg.ID()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.description = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.symbol, _x.layer_id.data, _x.enabled, _x.priority, _x.operation,) = _get_struct_HIBHB().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HIBHB().pack(_x.symbol, _x.layer_id.data, _x.enabled, _x.priority, _x.operation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.layer_id is None:
        self.layer_id = agv_msgs.msg.ID()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.description = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.symbol, _x.layer_id.data, _x.enabled, _x.priority, _x.operation,) = _get_struct_HIBHB().unpack(str[start:end])
      self.enabled = bool(self.enabled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_HIBHB = None
def _get_struct_HIBHB():
    global _struct_HIBHB
    if _struct_HIBHB is None:
        _struct_HIBHB = struct.Struct("<HIBHB")
    return _struct_HIBHB
