# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_msgs/WaypointStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import agv_msgs.msg

class WaypointStatus(genpy.Message):
  _md5sum = "62191f205a4471b269c61732e2f09cee"
  _type = "agv_msgs/WaypointStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """agv_msgs/ID goal_id
uint8 state # contins actionlib::SimpleClientGoalState state
float32 radius
bool road
bool intersection
================================================================================
MSG: agv_msgs/ID
 uint32 data

 uint32 INVALID_ID=0
"""
  __slots__ = ['goal_id','state','radius','road','intersection']
  _slot_types = ['agv_msgs/ID','uint8','float32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal_id,state,radius,road,intersection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goal_id is None:
        self.goal_id = agv_msgs.msg.ID()
      if self.state is None:
        self.state = 0
      if self.radius is None:
        self.radius = 0.
      if self.road is None:
        self.road = False
      if self.intersection is None:
        self.intersection = False
    else:
      self.goal_id = agv_msgs.msg.ID()
      self.state = 0
      self.radius = 0.
      self.road = False
      self.intersection = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IBf2B().pack(_x.goal_id.data, _x.state, _x.radius, _x.road, _x.intersection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_id is None:
        self.goal_id = agv_msgs.msg.ID()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.goal_id.data, _x.state, _x.radius, _x.road, _x.intersection,) = _get_struct_IBf2B().unpack(str[start:end])
      self.road = bool(self.road)
      self.intersection = bool(self.intersection)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IBf2B().pack(_x.goal_id.data, _x.state, _x.radius, _x.road, _x.intersection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal_id is None:
        self.goal_id = agv_msgs.msg.ID()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.goal_id.data, _x.state, _x.radius, _x.road, _x.intersection,) = _get_struct_IBf2B().unpack(str[start:end])
      self.road = bool(self.road)
      self.intersection = bool(self.intersection)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IBf2B = None
def _get_struct_IBf2B():
    global _struct_IBf2B
    if _struct_IBf2B is None:
        _struct_IBf2B = struct.Struct("<IBf2B")
    return _struct_IBf2B
